### ISSUE TITLE
TypingDNA sample various issues

### ISSUE THREAD

**Issue by Glomels** [azure-ad-b2c/partner-integrations#5]
While implementing the TypingDNA sample, I ran into multiple issues, including the folowing:

- Relying party files don't have script execution enabled. Also, since the MFA starter pack content definitions are not the contract versions, so maybe this sample should just override the DataUris in the Extensions policy.
- Both user journeys have a repeated step with order value of 3.

If you like I can take some time later in the day to open a PR addressing these issues.

**Comment by JasSuri** [comment]
Thanks, i made changes that should fix all of that, please review.

**Comment by Glomels** [comment]
Yeah, looks good. Thanks!
